2023-03-25 12:10:03,241 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Configure stats pid to 1334
2023-03-25 12:10:03,241 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-25 12:10:03,241 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-25 12:10:03,241 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-25 12:10:03,241 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 12:10:03,241 INFO    MainThread:1334 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_121003-npapwiv1/logs/debug.log
2023-03-25 12:10:03,242 INFO    MainThread:1334 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_121003-npapwiv1/logs/debug-internal.log
2023-03-25 12:10:03,242 INFO    MainThread:1334 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb77c2dcd60>
2023-03-25 12:10:03,242 INFO    MainThread:1334 [wandb_init.py:init():546] calling init triggers
2023-03-25 12:10:03,242 INFO    MainThread:1334 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 8009, 'tgt_vocab_size': 8009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 750, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-25 12:10:03,242 INFO    MainThread:1334 [wandb_init.py:init():602] starting backend
2023-03-25 12:10:03,242 INFO    MainThread:1334 [wandb_init.py:init():606] setting up manager
2023-03-25 12:10:03,247 INFO    MainThread:1334 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-25 12:10:03,252 INFO    MainThread:1334 [wandb_init.py:init():613] backend started and connected
2023-03-25 12:10:03,262 INFO    MainThread:1334 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-03-25 12:10:03,263 INFO    MainThread:1334 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-25 12:10:03,263 INFO    MainThread:1334 [wandb_init.py:init():701] updated telemetry
2023-03-25 12:10:03,362 INFO    MainThread:1334 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-25 12:10:03,510 INFO    MainThread:1334 [wandb_run.py:_on_init():2133] communicating current version
2023-03-25 12:10:03,584 INFO    MainThread:1334 [wandb_run.py:_on_init():2142] got version response 
2023-03-25 12:10:03,584 INFO    MainThread:1334 [wandb_init.py:init():789] starting run threads in backend
2023-03-25 12:10:09,195 INFO    MainThread:1334 [wandb_run.py:_console_start():2114] atexit reg
2023-03-25 12:10:09,195 INFO    MainThread:1334 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-25 12:10:09,196 INFO    MainThread:1334 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-25 12:10:09,196 INFO    MainThread:1334 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-25 12:10:09,197 INFO    MainThread:1334 [wandb_init.py:init():831] run started, returning control to user process
2023-03-25 12:10:09,197 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:09,197 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:09,204 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:09,205 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:09,205 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:09,212 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:12,092 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:12,092 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:12,101 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:12,103 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:12,103 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:12,108 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:12,110 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:12,110 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:12,116 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:12,117 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:12,117 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:12,125 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:12,126 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:12,127 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:12,134 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:12,136 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:12,136 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:10:12,141 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:10:12,142 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:10:12,142 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:12:52,029 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:12:52,396 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:12:52,396 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:13:01,679 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:37:00,165 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:37:00,165 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:40:28,748 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:40:28,750 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:40:28,750 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:40:29,680 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:40:29,680 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:40:29,680 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:40:30,439 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:40:30,440 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:40:30,440 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:40:30,872 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:40:35,028 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:40:35,028 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:41:44,193 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:41:44,195 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:41:44,195 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:42:28,607 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:42:28,608 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:42:28,608 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:42:29,721 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 12:42:34,880 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 12:42:34,880 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 12:42:58,731 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:05:51,197 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:05:51,197 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 13:07:07,814 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:07:07,816 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:07:07,816 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 13:07:08,368 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:07:08,369 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:07:08,369 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 13:07:09,158 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:07:09,159 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:07:09,159 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 13:07:09,856 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:07:09,857 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:07:09,857 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 13:07:13,050 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:07:19,113 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:07:19,113 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 13:07:26,241 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:07:26,244 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:07:26,244 INFO    MainThread:1334 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-25 13:08:17,002 INFO    MainThread:1334 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-25 13:08:17,016 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Configure stats pid to 1334
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_130817-a0f3qxs0/logs/debug.log
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_130817-a0f3qxs0/logs/debug-internal.log
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_init.py:init():546] calling init triggers
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 8009, 'tgt_vocab_size': 8009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 750, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-25 13:08:17,017 INFO    MainThread:1334 [wandb_init.py:init():568] re-initializing run, found existing run on stack: npapwiv1
2023-03-25 13:08:17,019 INFO    MainThread:1334 [wandb_run.py:_finish():1854] finishing run saturi/model_exp_spm_8000_0325_final/npapwiv1
2023-03-25 13:08:17,020 INFO    MainThread:1334 [jupyter.py:save_history():445] not saving jupyter history
2023-03-25 13:08:17,020 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:08:17,020 INFO    MainThread:1334 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-03-25 13:08:17,020 INFO    MainThread:1334 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-25 13:08:17,020 INFO    MainThread:1334 [wandb_run.py:_restore():2066] restore
2023-03-25 13:08:17,020 INFO    MainThread:1334 [wandb_run.py:_restore():2072] restore done
2023-03-25 13:10:49,092 WARNING MsgRouterThr:1334 [router.py:message_loop():77] message_loop has been closed
2023-03-25 13:10:58,072 INFO    MainThread:1334 [wandb_run.py:_restore():2066] restore
2023-03-25 13:10:58,072 INFO    MainThread:1334 [wandb_run.py:_restore():2072] restore done
2023-03-25 13:10:58,117 ERROR   MainThread:1334 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2092, in _atexit_cleanup
    self._on_finish()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2325, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2290, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1144, in init
    run = wi.init()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 581, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 370, in wrapper
    return func(self, *args, **kwargs)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 333, in wrapper
    return func(self, *args, **kwargs)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1845, in finish
    return self._finish(exit_code, quiet)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1860, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2103, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 259, in cleanup
    self.interface.join()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 638, in join
    super().join()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 741, in join
    _ = self._communicate_shutdown()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 551, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 285, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-03-25 13:11:40,373 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Configure stats pid to 1334
2023-03-25 13:11:40,374 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-25 13:11:40,374 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-25 13:11:40,374 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-25 13:11:40,374 INFO    MainThread:1334 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-25 13:11:40,374 INFO    MainThread:1334 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_131140-916gp048/logs/debug.log
2023-03-25 13:11:40,374 INFO    MainThread:1334 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230325_131140-916gp048/logs/debug-internal.log
2023-03-25 13:11:40,375 INFO    MainThread:1334 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb5e4c333d0>
2023-03-25 13:11:40,375 INFO    MainThread:1334 [wandb_init.py:init():546] calling init triggers
2023-03-25 13:11:40,375 INFO    MainThread:1334 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 8009, 'tgt_vocab_size': 8009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 750, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-25 13:11:40,375 INFO    MainThread:1334 [wandb_init.py:init():568] re-initializing run, found existing run on stack: npapwiv1
2023-03-25 13:11:40,377 INFO    MainThread:1334 [wandb_run.py:_finish():1854] finishing run saturi/model_exp_spm_8000_0325_final/npapwiv1
2023-03-25 13:11:40,377 INFO    MainThread:1334 [jupyter.py:save_history():445] not saving jupyter history
2023-03-25 13:11:40,377 INFO    MainThread:1334 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-25 13:11:40,377 INFO    MainThread:1334 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
