2023-03-29 20:28:06,435 INFO    MainThread:8233 [wandb_setup.py:_flush():76] Configure stats pid to 8233
2023-03-29 20:28:06,435 INFO    MainThread:8233 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-29 20:28:06,435 INFO    MainThread:8233 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230329_202806-mdiitljx/logs/debug.log
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230329_202806-mdiitljx/logs/debug-internal.log
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f270824ab50>
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_init.py:init():546] calling init triggers
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 16009, 'tgt_vocab_size': 16009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 8500, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_init.py:init():602] starting backend
2023-03-29 20:28:06,436 INFO    MainThread:8233 [wandb_init.py:init():606] setting up manager
2023-03-29 20:28:06,441 INFO    MainThread:8233 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-29 20:28:06,446 INFO    MainThread:8233 [wandb_init.py:init():613] backend started and connected
2023-03-29 20:28:06,458 INFO    MainThread:8233 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-03-29 20:28:06,458 INFO    MainThread:8233 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-29 20:28:06,458 INFO    MainThread:8233 [wandb_init.py:init():701] updated telemetry
2023-03-29 20:28:06,569 INFO    MainThread:8233 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-29 20:28:06,710 INFO    MainThread:8233 [wandb_run.py:_on_init():2133] communicating current version
2023-03-29 20:28:06,840 INFO    MainThread:8233 [wandb_run.py:_on_init():2142] got version response 
2023-03-29 20:28:06,840 INFO    MainThread:8233 [wandb_init.py:init():789] starting run threads in backend
2023-03-29 20:28:16,071 WARNING MsgRouterThr:8233 [router.py:message_loop():77] message_loop has been closed
2023-03-29 20:28:21,868 ERROR   MainThread:8233 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1144, in init
    run = wi.init()
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 801, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/seuyon0101/anaconda3/envs/saturi/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
