2023-03-28 10:27:35,360 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Configure stats pid to 2100
2023-03-28 10:27:35,361 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-28 10:27:35,361 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-28 10:27:35,361 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-28 10:27:35,361 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-28 10:27:35,361 INFO    MainThread:2100 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230328_102735-jwsigt94/logs/debug.log
2023-03-28 10:27:35,361 INFO    MainThread:2100 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230328_102735-jwsigt94/logs/debug-internal.log
2023-03-28 10:27:35,361 INFO    MainThread:2100 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9390802bb0>
2023-03-28 10:27:35,362 INFO    MainThread:2100 [wandb_init.py:init():546] calling init triggers
2023-03-28 10:27:35,362 INFO    MainThread:2100 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 8010, 'tgt_vocab_size': 8009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 8000, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-28 10:27:35,362 INFO    MainThread:2100 [wandb_init.py:init():568] re-initializing run, found existing run on stack: ms90tjt5
2023-03-28 10:27:35,364 INFO    MainThread:2100 [wandb_run.py:_finish():1854] finishing run saturi/model_exp_cmsp_8000_0328_stdn_final_v3v/ms90tjt5
2023-03-28 10:27:35,364 INFO    MainThread:2100 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-28 10:27:35,365 INFO    MainThread:2100 [wandb_run.py:_restore():2066] restore
2023-03-28 10:27:35,365 INFO    MainThread:2100 [wandb_run.py:_restore():2072] restore done
2023-03-28 10:27:39,847 INFO    MainThread:2100 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-03-28 10:27:39,848 INFO    MainThread:2100 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-03-28 10:27:39,852 INFO    MainThread:2100 [wandb_run.py:_footer_sync_info():3380] logging synced files
2023-03-28 10:27:39,855 INFO    MainThread:2100 [wandb_init.py:init():602] starting backend
2023-03-28 10:27:39,855 INFO    MainThread:2100 [wandb_init.py:init():606] setting up manager
2023-03-28 10:27:39,859 INFO    MainThread:2100 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-28 10:27:39,862 INFO    MainThread:2100 [wandb_init.py:init():613] backend started and connected
2023-03-28 10:27:39,872 INFO    MainThread:2100 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-03-28 10:27:39,872 INFO    MainThread:2100 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-28 10:27:39,872 INFO    MainThread:2100 [wandb_init.py:init():701] updated telemetry
2023-03-28 10:27:40,075 INFO    MainThread:2100 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-28 10:27:40,988 INFO    MainThread:2100 [wandb_run.py:_on_init():2133] communicating current version
2023-03-28 10:27:41,056 INFO    MainThread:2100 [wandb_run.py:_on_init():2142] got version response 
2023-03-28 10:27:41,056 INFO    MainThread:2100 [wandb_init.py:init():789] starting run threads in backend
2023-03-28 10:27:44,718 INFO    MainThread:2100 [wandb_run.py:_console_start():2114] atexit reg
2023-03-28 10:27:44,718 INFO    MainThread:2100 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-28 10:27:44,718 INFO    MainThread:2100 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-28 10:27:44,718 INFO    MainThread:2100 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-28 10:27:44,719 INFO    MainThread:2100 [wandb_init.py:init():831] run started, returning control to user process
2023-03-28 10:28:02,802 INFO    MainThread:2100 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-28 10:28:02,802 INFO    MainThread:2100 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-28 10:28:19,955 INFO    MainThread:2100 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-28 10:28:19,962 INFO    MainThread:2100 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-28 10:28:19,962 INFO    MainThread:2100 [wandb_init.py:_pause_backend():417] pausing backend
2023-03-28 10:28:27,846 INFO    MainThread:2100 [wandb_init.py:_resume_backend():422] resuming backend
2023-03-28 10:28:27,861 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Configure stats pid to 2100
2023-03-28 10:28:27,861 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/.config/wandb/settings
2023-03-28 10:28:27,861 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Loading settings from /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/settings
2023-03-28 10:28:27,861 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-28 10:28:27,861 INFO    MainThread:2100 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-28 10:28:27,861 INFO    MainThread:2100 [wandb_init.py:_log_setup():506] Logging user logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230328_102827-tbeyp9j0/logs/debug.log
2023-03-28 10:28:27,861 INFO    MainThread:2100 [wandb_init.py:_log_setup():507] Logging internal logs to /home/seuyon0101/aiffel/saturi/notebook/Model/wandb/run-20230328_102827-tbeyp9j0/logs/debug-internal.log
2023-03-28 10:28:27,862 INFO    MainThread:2100 [wandb_init.py:init():546] calling init triggers
2023-03-28 10:28:27,862 INFO    MainThread:2100 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'model_name': 'Vanilla_Transformer', 'n_layers': 6, 'd_model': 512, 'n_heads': 8, 'd_ff': 2048, 'src_vocab_size': 8010, 'tgt_vocab_size': 8009, 'pos_len': 512, 'dropout': 0.2, 'shared': True, 'warmups': 8000, 'epochs': 1, 'optimizer': 'ADAM', 'loss': 'SparseCategoricalCrossentropy', 'metric': 'bleu'}
2023-03-28 10:28:27,862 INFO    MainThread:2100 [wandb_init.py:init():568] re-initializing run, found existing run on stack: jwsigt94
2023-03-28 10:28:27,864 INFO    MainThread:2100 [wandb_run.py:_finish():1854] finishing run saturi/model_exp_cmsp_8000_0328_stdn_final_v3v/jwsigt94
2023-03-28 10:28:27,865 INFO    MainThread:2100 [jupyter.py:save_history():445] not saving jupyter history
2023-03-28 10:28:27,865 INFO    MainThread:2100 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-03-28 10:28:27,865 INFO    MainThread:2100 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-03-28 10:28:27,866 INFO    MainThread:2100 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-28 10:28:27,866 INFO    MainThread:2100 [wandb_run.py:_restore():2066] restore
2023-03-28 10:28:27,866 INFO    MainThread:2100 [wandb_run.py:_restore():2072] restore done
2023-03-28 10:28:31,792 INFO    MainThread:2100 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-03-28 10:28:31,792 INFO    MainThread:2100 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-03-28 10:28:31,794 INFO    MainThread:2100 [wandb_run.py:_footer_sync_info():3380] logging synced files
